name = "doctor-notifier-webhook"
main = "src/index.js"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "STORAGE"
id = "9cda716cb66f45eb9ccf7d8bf1d99f8a"
